CREATE TABLE IF NOT EXISTS vessels (
  id TEXT PRIMARY KEY,
  boat_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS buoys (
  id TEXT PRIMARY KEY,
  vessel_id TEXT REFERENCES vessels(id) ON DELETE SET NULL,
  label TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS buoy_contacts (
  id BIGSERIAL PRIMARY KEY,
  buoy_id TEXT NOT NULL REFERENCES buoys(id) ON DELETE CASCADE,
  contact_type TEXT NOT NULL,
  contact_value TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sos_events (
  id BIGSERIAL PRIMARY KEY,
  vessel_id TEXT NOT NULL REFERENCES vessels(id) ON DELETE CASCADE,
  buoy_id TEXT REFERENCES buoys(id) ON DELETE SET NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
